git merge release/lab_intro --allow-unrelated-histories
git merge release/lab_debug --allow-unrelated-histories
git merge release/lab_memory --allow-unrelated-histories
git merge release/lab_inheritance --allow-unrelated-histories
git merge release/lab_quacks --allow-unrelated-histories
git merge release/lab_trees --allow-unrelated-histories
git merge release/lab_huffman --allow-unrelated-histories
git merge release/lab_avl --allow-unrelated-histories
git merge release/lab_btree --allow-unrelated-histories
git merge release/lab_hash --allow-unrelated-histories
git merge release/lab_heaps --allow-unrelated-histories
git merge release/lab_dict --allow-unrelated-histories
git merge release/lab_ml --allow-unrelated-histories
git merge release/lab_flow --allow-unrelated-histories
git merge release/mp_intro --allow-unrelated-histories
git merge release/mp_stickers --allow-unrelated-histories
git merge release/mp_lists --allow-unrelated-histories
git merge release/mp_traversals --allow-unrelated-histories
git merge release/mp_mosaics --allow-unrelated-histories
git merge release/mp_mazes --allow-unrelated-histories